# Generated by Django 2.2.9 on 2021-09-29 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copyright',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Copyright'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Publication'),
        ),
    ]
