# Generated by Django 2.2.9 on 2021-09-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='名称')),
                ('rank', models.IntegerField(choices=[(0, 'none'), (1, 'ACE'), (2, 'TWO'), (3, 'THREE'), (4, 'FOUR'), (5, 'FIVE'), (6, 'SIX'), (7, 'SEVEN'), (8, 'EIGHT'), (9, 'NINE'), (10, 'TEN'), (11, 'JACK'), (12, 'QUEEN'), (13, 'KING')], default=0, verbose_name='点数')),
                ('suit', models.IntegerField(choices=[(0, '无'), (1, '黑桃'), (2, '红桃'), (3, '方块'), (4, '梅花')], default=0, verbose_name='花色')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='功能')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='名称')),
                ('group', models.IntegerField(choices=[(1, '魏'), (2, '蜀'), (3, '吴'), (4, '群'), (5, '晋')], verbose_name='势力')),
                ('gender', models.IntegerField(choices=[(1, '男'), (0, '女')], verbose_name='性别')),
            ],
        ),
    ]
